/**
 * Migration 38 — char : ref_mutations
 *
 * Crée la table ref_mutations et seed les 33 mutations du catalogue Polaris.
 * Source : mutation_bdd.js (32 mutations) + muta_033 Radiation (ajout manuel).
 *
 * PK : muta_numero TEXT (ex: 'muta_001')
 *
 * Colonnes modificateurs d'attributs : mod_for, mod_coo, mod_con, mod_pre, mod_vol, mod_per
 * Colonnes modificateurs de compétences : mod_acrobatie, mod_escalade, mod_evasion, mod_discretion
 * Colonnes résistances : res_armure, res_choc, res_feu, res_froid, res_drogue_maladie, res_radiation
 * Arme naturelle : nom_arme_naturelle, degats_physiques, degats_choc
 * Cumul : stack_mod_val (bonus par prise supplémentaire), stack_target_col (colonne cible)
 *
 * linked_skill : nom de la compétence débloquée par cette mutation (texte libre).
 *   Utilisé pour information — le lien fonctionnel passe par ref_skill_requirements.
 *
 * down : supprime la table (CASCADE sur ref_skill_requirements).
 */

const MUTATIONS = [
  {
    "muta_numero": "muta_001",
    "nom": "Adaptation extérieure",
    "description": "Le personnage possède une résistance aux effets néfastes de la Surface (radiations, acidité de l'air, altération moléculaire…). Le niveau de la compétence indique le nombre d'heures d'exposition possible. Après exposition, nécessite un repos de 3x la durée passée à l'extérieur.",
    "linked_skill": "Adaptation extérieure",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_002",
    "nom": "Amphibie",
    "description": "Respiration sous-marine. Supporte pression et froid. Profondeur max : (niveau Hybride) x 500m. Max Constitution mètres si niveau < 1. Maîtrise limitée au niveau +0.",
    "linked_skill": "Hybride",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_003",
    "nom": "Androgyne",
    "description": "Physiquement, le personnage tient des deux sexes.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_004",
    "nom": "Asexué",
    "description": "Le personnage est né sans sexe. Le personnage est donc stérile.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_005",
    "nom": "Autofécondation",
    "description": "Le personnage ne possède pas d'organes reproducteurs mais peut s'autoféconder et mettre un enfant au monde.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_006",
    "nom": "Caractère félin",
    "description": "Aspect animal. Pas de vertige. Bonus de 1 PC sur Griffes et Vision nocturne.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 2,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 3,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_007",
    "nom": "Caractère canin",
    "description": "Aspect animal. Bonus de +3 Perception (odorat). Accès libre à la mutation Crocs.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 1,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_008",
    "nom": "Caractère reptilien",
    "description": "Aspect animal. Bonus de +3 Perception (odorat via langue bifide). Capacité à se faufiler.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 1,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 3,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_009",
    "nom": "Caractère simiesque",
    "description": "Aspect animal. Accès libre à la mutation Queue.",
    "linked_skill": null,
    "mod_for": 1,
    "mod_coo": 1,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 3,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_010",
    "nom": "Contact corrosif",
    "description": "Sécrétion corrosive (1D10 dégâts). Dure 3D6 tours sauf si nettoyé. Indépendant des autres actions.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": "Contact corrosif",
    "degats_physiques": "1D10",
    "degats_choc": null,
    "stack_mod_val": 3,
    "stack_target_col": "degats_physiques"
  },
  {
    "muta_numero": "muta_011",
    "nom": "Contagion",
    "description": "Porteur sain de maladies (Grippe bleue). Immunité totale aux maladies. Virulence selon difficulté : +0 (1D6), -3 (2D6), -5 (3D6), -7 (4D6), -10 (5D6).",
    "linked_skill": "Contagion",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 3,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_012",
    "nom": "Corne",
    "description": "Petite corne frontale. Utilisable après une saisie. +1D6 Choc si le coup porte à la tête.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": "Corne",
    "degats_physiques": "1D10",
    "degats_choc": "1D6",
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_013",
    "nom": "Crocs",
    "description": "Dents tranchantes. Utilisable après une saisie.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": "Crocs",
    "degats_physiques": "1D10+3",
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_014",
    "nom": "Difformité légère",
    "description": "Difformité physique au choix du joueur et du MJ. Malus cumulatif.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": -1,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_015",
    "nom": "Difformité importante",
    "description": "Difformité physique majeure au choix du joueur et du MJ. Malus cumulatif.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": -2,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_016",
    "nom": "Empathie",
    "description": "Accès à la compétence Empathie (VOL/PRE). Permet de ressentir/modifier les émotions. Portée : Corail (-7), Animaux (-3), Humains (Volonté cible / 2).",
    "linked_skill": "Empathie",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_017",
    "nom": "Excroissance osseuse rétractable",
    "description": "Une lame osseuse jaillit de l'avant-bras. S'utilise avec la compétence Combat à mains nues.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": "Excroissance osseuse",
    "degats_physiques": "2D10",
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_018",
    "nom": "Griffes",
    "description": "Armes naturelles. Malus de -3 pour les tests impliquant une dextérité manuelle (crochetage, vol, etc.).",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 3,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": "Griffes",
    "degats_physiques": "1D10+3",
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_019",
    "nom": "Instabilité moléculaire",
    "description": "En cas d'échec critique (96-00), le personnage se dématérialise pendant 1D10 min. Il ne peut plus agir ni subir de dégâts physiques, mais peut subir des attaques mentales/Polaris.",
    "linked_skill": "Contrôle moléculaire",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_020",
    "nom": "Métamorphe",
    "description": "Peut modifier son apparence et sa structure. Permet de déplacer jusqu'à 2 points d'Attributs (ex: -1 FOR / +1 COO). Nécessite 1D10 tours de concentration.",
    "linked_skill": "Métamorphe",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_021",
    "nom": "Nictope",
    "description": "Le personnage voit parfaitement dans le noir. En revanche, il est ébloui par toute lumière vive (malus de -5 à toutes ses actions).",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_022",
    "nom": "Ouïe fine",
    "description": "Le personnage entend des sons inaudibles pour les autres. Bonus de +3 aux tests de Perception basés sur l'ouïe.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_023",
    "nom": "Peau renforcée",
    "description": "La peau est couverte de plaques cornées ou d'écailles. Offre une protection naturelle. Cumulable : chaque sélection supplémentaire ajoute +2 à l'armure.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 3,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": 2,
    "stack_target_col": "res_armure"
  },
  {
    "muta_numero": "muta_024",
    "nom": "Peau visqueuse",
    "description": "La peau sécrète un mucus glissant. Bonus de +3 pour se libérer d'une saisie ou se faufiler.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 3,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_025",
    "nom": "Purulence",
    "description": "Peau couverte de bubons et plaies suintantes. Très contagieux. Bonus de +3 en Résistance aux maladies.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": -2,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 3,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_026",
    "nom": "Queue",
    "description": "Queue d'environ 1m. Améliore l'équilibre. Peut être utilisée pour saisir un objet léger.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 3,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_027",
    "nom": "Régénération",
    "description": "Récupération de 1 pt de Vie / heure. Bonus de +3 aux tests de résistance contre l'infection. Les membres perdus repoussent en 1D10 semaines.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_028",
    "nom": "Résistance naturelle",
    "description": "Résistance accrue à un élément spécifique (Feu, Froid, Drogues, etc.). Bonus de +3 à chaque sélection.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": 3,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_029",
    "nom": "Sensibilité au Polaris",
    "description": "Débloque l'accès aux pouvoirs du Polaris. Permet l'achat de toute compétence liée à la Force ou à l'Écho Polaris.",
    "linked_skill": "Maîtrise de l'Écho Polaris, Maîtrise de la Force Polaris",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_030",
    "nom": "Sixième sens",
    "description": "Le personnage ne peut jamais être surpris. Il ressent le danger imminent.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_031",
    "nom": "Sonar",
    "description": "Émission d'ultrasons permettant de repérer les formes et les volumes, même dans le noir total ou l'eau trouble. Portée : 100m (air) / 500m (eau).",
    "linked_skill": "Sonar",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": null,
    "degats_choc": null,
    "stack_mod_val": null,
    "stack_target_col": null
  },
  {
    "muta_numero": "muta_032",
    "nom": "Squelette renforcé",
    "description": "Les os sont plus denses ou doublés de métal/cartilage. Bonus de +2 en Résistance Dommages et +3 en Résistance Choc. Cumulable : +1 à chaque résistance par sélection supplémentaire.",
    "linked_skill": null,
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 2,
    "res_choc": 3,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": "Coup de poing renforcé",
    "degats_physiques": "1D6",
    "degats_choc": "1D10",
    "stack_mod_val": 1,
    "stack_target_col": "MULTI"
  },
  {
    "muta_numero": "muta_033",
    "nom": "Radiation",
    "description": "Donne accès à la Compétence spéciale Radiations (CON/VOL, -3) à coût doublé. Permet de libérer un flot de radiations dans l'organisme d'une victime par simple contact. Intensité : 2D6 + modificateur de réussite. Chaque nouvelle prise augmente l'intensité de 3 points. Octroie gratuitement la mutation Résistance aux radiations.",
    "linked_skill": "Radiations",
    "mod_for": 0,
    "mod_coo": 0,
    "mod_con": 0,
    "mod_pre": 0,
    "mod_vol": 0,
    "mod_per": 0,
    "mod_acrobatie": 0,
    "mod_escalade": 0,
    "mod_evasion": 0,
    "mod_discretion": 0,
    "res_armure": 0,
    "res_choc": 0,
    "res_feu": 0,
    "res_froid": 0,
    "res_drogue_maladie": 0,
    "res_radiation": 0,
    "nom_arme_naturelle": null,
    "degats_physiques": "2D6",
    "degats_choc": null,
    "stack_mod_val": 3,
    "stack_target_col": "degats_physiques"
  }
];

export const up = async (knex) => {
  await knex.schema.createTable('ref_mutations', (table) => {
    table.text('muta_numero').primary()
    table.text('nom').notNullable()
    table.text('description').defaultTo(null)
    table.text('linked_skill').defaultTo(null)
    table.integer('mod_for').defaultTo(0)
    table.integer('mod_coo').defaultTo(0)
    table.integer('mod_con').defaultTo(0)
    table.integer('mod_pre').defaultTo(0)
    table.integer('mod_vol').defaultTo(0)
    table.integer('mod_per').defaultTo(0)
    table.integer('mod_acrobatie').defaultTo(0)
    table.integer('mod_escalade').defaultTo(0)
    table.integer('mod_evasion').defaultTo(0)
    table.integer('mod_discretion').defaultTo(0)
    table.integer('res_armure').defaultTo(0)
    table.integer('res_choc').defaultTo(0)
    table.integer('res_feu').defaultTo(0)
    table.integer('res_froid').defaultTo(0)
    table.integer('res_drogue_maladie').defaultTo(0)
    table.integer('res_radiation').defaultTo(0)
    table.text('nom_arme_naturelle').defaultTo(null)
    table.text('degats_physiques').defaultTo(null)
    table.text('degats_choc').defaultTo(null)
    table.integer('stack_mod_val').defaultTo(null)
    table.text('stack_target_col').defaultTo(null)
  })

  await knex('ref_mutations').insert(MUTATIONS)
}

export const down = async (knex) => {
  await knex.schema.dropTableIfExists('ref_mutations')
}
