// 092_ref_advantages.cjs — v3

const ADVANTAGES = [
  // ─── adv_001 : Allié ou Fournisseur supplémentaire ───
  {
    advantage_id: "adv_001",
    name: "Allié ou Fournisseur supplémentaire",
    type: "advantage",
    description: "Permet d'avoir un Allié supplémentaire (voir le chapitre Professions).",
    cost_pc: 2,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: { allies_fournisseurs: 1 },
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_002 : Ambidextre ───
  {
    advantage_id: "adv_002",
    name: "Ambidextre",
    type: "advantage",
    description: "Le personnage peut utiliser sa main droite et sa main gauche avec autant d'efficacité.",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: { hand_pref: "A" },
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_003 : Argent supplémentaire ───
  {
    advantage_id: "adv_003",
    name: "Argent supplémentaire",
    type: "advantage",
    description: "Le personnage reçoit l'équivalent de 1 000 sols supplémentaires en plaquettes ou en objets de troc.",
    cost_pc: 1,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: 1000,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_004 : Bilingue ───
  {
    advantage_id: "adv_004",
    name: "Bilingue",
    type: "advantage",
    description: "Le personnage peut choisir deux langues maternelles (obligatoirement une langue commune et courante).",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Deux langues maternelles au lieu d'une. Une langue commune et courante obligatoire."
  },

  // ─── adv_005 : Bonne mémoire ───
  {
    advantage_id: "adv_005",
    name: "Bonne mémoire",
    type: "advantage",
    description: "Le personnage possède une mémoire particulièrement bonne. +3 pour se rappeler un fait précis, +5 pour apprendre par cœur.",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { recall: 3, memorize: 5 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_006 : Bons réflexes ───
  {
    advantage_id: "adv_006",
    name: "Bons réflexes",
    type: "advantage",
    description: "Le personnage gagne un bonus de +3 à sa Réaction.",
    cost_pc: 2,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: "reaction", mod_value: 3,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_007 à adv_011 : Carte au trésor ───
  ...[1,2,3,4,5].map(n => ({
    advantage_id: `adv_${String(7+n-1).padStart(3,'0')}`,
    name: `Carte au trésor (${n} PC)`,
    type: "advantage",
    description: `Le personnage possède une carte pouvant le mener à un trésor${n===5?" (au cœur d'une petite campagne)":n===1?" (petit scénario)":""}.`,
    cost_pc: n,
    is_unique: false,
    family: "Carte au trésor", family_limit: 1, subtype: String(n),
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: `${n===5?"Campagne":n===1?"Petit scénario":"Scénario modéré à important"}.`
  })),

  // ─── adv_012 à adv_016 : Concession ───
  ...[1,2,3,4,5].map(n => ({
    advantage_id: `adv_${String(12+n-1).padStart(3,'0')}`,
    name: `Concession (${n} PC)`,
    type: "advantage",
    description: `Le personnage possède une concession sur un territoire${n===5?" de très grande valeur":n===1?" de faible valeur":""}.`,
    cost_pc: n,
    is_unique: false,
    family: "Concession", family_limit: 1, subtype: String(n),
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Concession territoriale exploitable."
  })),

  // ─── adv_017 : Contacts ───
  {
    advantage_id: "adv_017",
    name: "Contacts",
    type: "advantage",
    description: "Le personnage bénéficie de 2 Contacts supplémentaires (voir le chapitre Professions).",
    cost_pc: 1,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: { contacts: 2 },
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_018 : Dur à cuire ───
  {
    advantage_id: "adv_018",
    name: "Dur à cuire",
    type: "advantage",
    description: "Le personnage résiste plus facilement aux blessures physiques. Il gagne un -1 à sa Résistance aux Dommages.",
    cost_pc: 2,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: "damage", mod_res_value: -1,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_019 : Fausse identité ───
  {
    advantage_id: "adv_019",
    name: "Fausse identité",
    type: "advantage",
    description: "Le personnage possède une fausse identité. Le joueur est libre de la choisir avec l'accord du MJ.",
    cost_pc: 2,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Fausse identité au choix du joueur (accord MJ)."
  },

  // ─── adv_020 : Formation ───
  {
    advantage_id: "adv_020",
    name: "Formation",
    type: "advantage",
    description: "Le personnage a suivi une formation ou un entraînement spécial. +7 points de Compétence. +1 an d'âge par 2 Formations.",
    cost_pc: 1,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: 7,
    mod_age: 1,
    special_rule: "Toute Compétence, accord MJ. +1 an d'âge par 2 Formations."
  },

  // ─── adv_021 : Homo delphinus ───
  {
    advantage_id: "adv_021",
    name: "Homo delphinus",
    type: "advantage",
    description: "Le personnage gagne un bonus de +10 à son Attribut Souffle.",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: "breath", mod_value: 10,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_022 : Increvable ───
  {
    advantage_id: "adv_022",
    name: "Increvable",
    type: "advantage",
    description: "Le personnage résiste bien à la Fatigue. Compteur de Fatigue : +3/+0/-5.",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { fatigue: [3, 0, -5] },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Si règles avancées non utilisées : +3 aux Tests de résistance à l'effort et à la fatigue."
  },

  // ─── adv_023 : Nerfs d'acier ───
  {
    advantage_id: "adv_023",
    name: "Nerfs d'acier",
    type: "advantage",
    description: "Le personnage gagne un bonus de +3 lors des Tests destinés à tester sa résistance au stress et à la peur.",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { stress_fear: 3 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_024 : Nyctalope ───
  {
    advantage_id: "adv_024",
    name: "Nyctalope",
    type: "advantage",
    description: "Réduit de moitié les pénalités dues à l'obscurité partielle.",
    cost_pc: 2,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Pénalités d'obscurité partielle divisées par 2."
  },

  // ─── adv_025 à adv_028 : Parts ───
  ...[1,2,3,4].map(n => ({
    advantage_id: `adv_${String(25+n-1).padStart(3,'0')}`,
    name: `Parts (${n} PC)`,
    type: "advantage",
    description: `Le personnage possède des parts dans une entreprise ou communauté. Revenu mensuel : ${n*250} sols.`,
    cost_pc: n,
    is_unique: false,
    family: "Parts", family_limit: 1, subtype: String(n),
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: n * 250,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Avantages si en relation avec l'entreprise. Revenu variable selon évolution financière."
  })),

  // ─── adv_029 : Rente ───
  {
    advantage_id: "adv_029",
    name: "Rente",
    type: "advantage",
    description: "Le personnage reçoit une rente mensuelle de 2D6 × 100 sols.",
    cost_pc: 3,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: "2D6*100",
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_030 : Résistance à la douleur ───
  {
    advantage_id: "adv_030",
    name: "Résistance à la douleur",
    type: "advantage",
    description: "Le personnage résiste particulièrement bien à la douleur. +2 Résistance au Choc, +3 aux Tests de Constitution ou Volonté pour résister à la douleur.",
    cost_pc: 1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: "shock", mod_res_value: 2,
    mod_conditions: { pain_con: 3, pain_vol: 3 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_031 à adv_034 : Résistance naturelle augmentée ───
  ...[
    { s: "poison", n: "031" },
    { s: "disease", n: "032" },
    { s: "radiation", n: "033" },
    { s: "drug", n: "034" }
  ].map(({s, n}) => ({
    advantage_id: `adv_${n}`,
    name: `Résistance naturelle augmentée (${s})`,
    type: "advantage",
    description: `La Résistance aux ${s}s du personnage est améliorée de 2 points.`,
    cost_pc: 1,
    is_unique: false,
    family: "Résistance naturelle augmentée", family_limit: 1, subtype: s,
    mod_attribute: null, mod_value: null,
    mod_resistance: s, mod_res_value: 2,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  })),

  // ─── adv_035 à adv_039 : Sens développé ───
  ...[
    { s: "sight", c: 2, n: "035" },
    { s: "hearing", c: 2, n: "036" },
    { s: "smell", c: 1, n: "037" },
    { s: "touch", c: 1, n: "038" },
    { s: "taste", c: 1, n: "039" }
  ].map(({s, c, n}) => ({
    advantage_id: `adv_${n}`,
    name: `Sens développé (${s})`,
    type: "advantage",
    description: `${s.charAt(0).toUpperCase()+s.slice(1)} particulièrement développé(e). Bonus de +3 lors des Tests impliquant directement ce sens.`,
    cost_pc: c,
    is_unique: false,
    family: "Sens développé", family_limit: 1, subtype: s,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { sense: s, bonus: 3 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  })),

  // ─── adv_040 : Titre ───
  {
    advantage_id: "adv_040",
    name: "Titre",
    type: "advantage",
    description: "Le personnage est doté d'un titre nobiliaire ou honorifique. Célébrité +12. Ignorez les points d'Influence.",
    cost_pc: 4,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: { celebrity: 12 },
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Ignorez les points d'Influence."
  }
];

const DISADVANTAGES = [
  // ─── adv_041 à adv_043 : Allergie ───
  {
    advantage_id: "adv_041",
    name: "Allergie (légère)",
    type: "disadvantage",
    description: "Le personnage est allergique à un produit commun. Gêne mineure : malus de -3.",
    cost_pc: -1,
    is_unique: false,
    family: "Allergie", family_limit: 1, subtype: "mild",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { penalty: -3 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Produit allergène à choisir."
  },
  {
    advantage_id: "adv_042",
    name: "Allergie (sévère)",
    type: "disadvantage",
    description: "Le personnage est allergique à un produit commun. Handicap sérieux : chances de réussite réduites de moitié.",
    cost_pc: -3,
    is_unique: false,
    family: "Allergie", family_limit: 1, subtype: "severe",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { success_rate: 0.5 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Produit allergène à choisir."
  },
  {
    advantage_id: "adv_043",
    name: "Allergie (fatale)",
    type: "disadvantage",
    description: "Le personnage est allergique à un produit commun. Peut entraîner la perte de conscience et la mort si exposition prolongée.",
    cost_pc: -6,
    is_unique: false,
    family: "Allergie", family_limit: 1, subtype: "fatal",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Perte de conscience/mort si exposition prolongée. Produit allergène à choisir."
  },

  // ─── adv_044 à adv_049 : Déséquilibre mental ───
  {
    advantage_id: "adv_044",
    name: "Cleptomanie",
    type: "disadvantage",
    description: "Le personnage ne peut s'empêcher de voler.",
    cost_pc: -2,
    is_unique: false,
    family: "Déséquilibre mental", family_limit: 1, subtype: "kleptomania",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Impulsion de vol incontrôlable. Au joueur d'incarner, crises possibles."
  },
  {
    advantage_id: "adv_045",
    name: "Mégalomanie",
    type: "disadvantage",
    description: "Le personnage est particulièrement arrogant et veut toujours s'imposer en tant que chef.",
    cost_pc: -2,
    is_unique: false,
    family: "Déséquilibre mental", family_limit: 1, subtype: "megalomania",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Se considère comme le meilleur. Veut toujours diriger. Crises possibles."
  },
  {
    advantage_id: "adv_046",
    name: "Paranoïa",
    type: "disadvantage",
    description: "Le personnage voit des ennemis et des complots partout.",
    cost_pc: -2,
    is_unique: false,
    family: "Déséquilibre mental", family_limit: 1, subtype: "paranoia",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Méfiance extrême. Voit des complots partout. Crises possibles."
  },
  {
    advantage_id: "adv_047",
    name: "Hallucination",
    type: "disadvantage",
    description: "Le personnage souffre d'hallucinations, pouvant être liées à son passé.",
    cost_pc: -2,
    is_unique: false,
    family: "Déséquilibre mental", family_limit: 1, subtype: "hallucination",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Hallucinations. Thème à développer avec le MJ. Crises possibles."
  },
  {
    advantage_id: "adv_048",
    name: "Pulsion psychopathe",
    type: "disadvantage",
    description: "Le personnage est soumis à des pulsions le poussant au meurtre.",
    cost_pc: -3,
    is_unique: false,
    family: "Déséquilibre mental", family_limit: 1, subtype: "psychopath",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Pulsions meurtrières. Au joueur d'incarner. Crises imposables par le MJ."
  },
  {
    advantage_id: "adv_049",
    name: "Double personnalité",
    type: "disadvantage",
    description: "Le personnage souffre d'un dédoublement de la personnalité.",
    cost_pc: -2,
    is_unique: false,
    family: "Déséquilibre mental", family_limit: 1, subtype: "split_personality",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Deuxième personnalité à définir avec le MJ. Crises possibles."
  },

  // ─── adv_050 : Ennemi héréditaire ───
  {
    advantage_id: "adv_050",
    name: "Ennemi héréditaire",
    type: "disadvantage",
    description: "Le personnage a un Ennemi qui veut vraiment sa perte (membre de la famille, directeur de société, pirate, etc.). Relativement puissant et souvent présent.",
    cost_pc: -3,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Ennemi puissant et récurrent. À définir avec le MJ."
  },

  // ─── adv_051 à adv_054 : Faiblesse naturelle ───
  ...[
    { s: "poison", n: "051" },
    { s: "disease", n: "052" },
    { s: "radiation", n: "053" },
    { s: "drug", n: "054" }
  ].map(({s, n}) => ({
    advantage_id: `adv_${n}`,
    name: `Faiblesse naturelle (${s})`,
    type: "disadvantage",
    description: `Le personnage souffre d'un modificateur de +2 sur sa Résistance aux ${s}s.`,
    cost_pc: -1,
    is_unique: false,
    family: "Faiblesse naturelle", family_limit: 1, subtype: s,
    mod_attribute: null, mod_value: null,
    mod_resistance: s, mod_res_value: 2,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  })),

  // ─── adv_055 : Froussard ───
  {
    advantage_id: "adv_055",
    name: "Froussard",
    type: "disadvantage",
    description: "Le personnage subit un malus de -3 lors des Tests destinés à tester sa résistance au stress et à la peur.",
    cost_pc: -1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { stress_fear: -3 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_056 à adv_057 : Infirmité ───
  {
    advantage_id: "adv_056",
    name: "Infirmité (5 PC)",
    type: "disadvantage",
    description: "Infirmité majeure : bras amputé/paralysé, surdité, muet…",
    cost_pc: -5,
    is_unique: false,
    family: "Infirmité", family_limit: 1, subtype: "major_5",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Infirmité majeure au choix. Exemples : bras amputé/paralysé, surdité, muet."
  },
  {
    advantage_id: "adv_057",
    name: "Infirmité (7 PC)",
    type: "disadvantage",
    description: "Infirmité majeure : aveugle, jambe amputée/paralysée…",
    cost_pc: -7,
    is_unique: false,
    family: "Infirmité", family_limit: 1, subtype: "major_7",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Infirmité majeure au choix. Exemples : aveugle, jambe amputée/paralysée."
  },

  // ─── adv_058 : Lent à réagir ───
  {
    advantage_id: "adv_058",
    name: "Lent à réagir",
    type: "disadvantage",
    description: "Le personnage subit un malus de -3 à sa Réaction.",
    cost_pc: -2,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: "reaction", mod_value: -3,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_059 : Opposants supplémentaires ───
  {
    advantage_id: "adv_059",
    name: "Opposants supplémentaires",
    type: "disadvantage",
    description: "Le personnage possède 2 Opposants supplémentaires.",
    cost_pc: -1,
    is_unique: false,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: { opponents: 2 },
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_060 : Petite nature ───
  {
    advantage_id: "adv_060",
    name: "Petite nature",
    type: "disadvantage",
    description: "Le personnage est très sensible à la douleur. -1 Résistance au Choc, -2 aux Tests de Constitution ou Volonté.",
    cost_pc: -1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: "shock", mod_res_value: -1,
    mod_conditions: { pain_con: -2, pain_vol: -2 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: null
  },

  // ─── adv_061 : Peu endurant ───
  {
    advantage_id: "adv_061",
    name: "Peu endurant",
    type: "disadvantage",
    description: "Le personnage se fatigue très vite. Compteur de Fatigue : -5/-10/-15.",
    cost_pc: -1,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { fatigue: [-5, -10, -15] },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Si règles avancées non utilisées : -3 aux Tests de résistance à l'effort et à la fatigue."
  },

  // ─── adv_062 à adv_066 : Phobies ───
  {
    advantage_id: "adv_062",
    name: "Phobie (créatures marines)",
    type: "disadvantage",
    description: "Phobie grave des créatures marines.",
    cost_pc: -1,
    is_unique: false,
    family: "Phobie", family_limit: 1, subtype: "sea_creatures",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Chances de réussite ÷2 face à la phobie. Informations déformées par le MJ."
  },
  {
    advantage_id: "adv_063",
    name: "Phobie (maladies)",
    type: "disadvantage",
    description: "Phobie grave des maladies.",
    cost_pc: -1,
    is_unique: false,
    family: "Phobie", family_limit: 1, subtype: "disease",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Chances de réussite ÷2 face à la phobie. Informations déformées par le MJ."
  },
  {
    advantage_id: "adv_064",
    name: "Phobie (mutants et hybrides)",
    type: "disadvantage",
    description: "Phobie grave des mutants, y compris les hybrides.",
    cost_pc: -2,
    is_unique: false,
    family: "Phobie", family_limit: 1, subtype: "mutants",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Chances de réussite ÷2 face à la phobie. Informations déformées par le MJ."
  },
  {
    advantage_id: "adv_065",
    name: "Phobie (claustrophobie)",
    type: "disadvantage",
    description: "Phobie grave des espaces réduits.",
    cost_pc: -3,
    is_unique: false,
    family: "Phobie", family_limit: 1, subtype: "claustrophobia",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Chances de réussite ÷2 face à la phobie. Informations déformées par le MJ."
  },
  {
    advantage_id: "adv_066",
    name: "Phobie (milieu sous-marin)",
    type: "disadvantage",
    description: "Phobie grave du milieu sous-marin (en armure, petit navire...).",
    cost_pc: -4,
    is_unique: false,
    family: "Phobie", family_limit: 1, subtype: "underwater",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Chances de réussite ÷2 face à la phobie. Informations déformées par le MJ."
  },

  // ─── adv_067 à adv_068 : Recherché ───
  {
    advantage_id: "adv_067",
    name: "Recherché (petite communauté)",
    type: "disadvantage",
    description: "Le personnage est recherché par une petite communauté. Sa tête est mise à prix.",
    cost_pc: -1,
    is_unique: false,
    family: "Recherché", family_limit: 1, subtype: "small_community",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Recherché par une petite communauté. Attention aux chasseurs de primes."
  },
  {
    advantage_id: "adv_068",
    name: "Recherché (nation / faction majeure)",
    type: "disadvantage",
    description: "Le personnage est recherché par une nation ou faction majeure.",
    cost_pc: -3,
    is_unique: false,
    family: "Recherché", family_limit: 1, subtype: "major_nation",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Recherché par une nation/faction majeure. Attention aux chasseurs de primes."
  },

  // ─── adv_069 à adv_070 : Secret ───
  {
    advantage_id: "adv_069",
    name: "Secret (+2 PC)",
    type: "disadvantage",
    description: "Le personnage a commis un acte terrible qui le hante.",
    cost_pc: -2,
    is_unique: false,
    family: "Secret", family_limit: 1, subtype: "minor",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Secret terrible. Fera l'objet d'un scénario."
  },
  {
    advantage_id: "adv_070",
    name: "Secret (+3 PC)",
    type: "disadvantage",
    description: "Le personnage a commis un acte terrible (crime odieux, viol, trahison...).",
    cost_pc: -3,
    is_unique: false,
    family: "Secret", family_limit: 1, subtype: "major",
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Secret terrible. Fera l'objet d'un scénario."
  },

  // ─── adv_071 à adv_075 : Sens diminué ───
  ...[
    { s: "sight", c: -2, n: "071" },
    { s: "hearing", c: -2, n: "072" },
    { s: "smell", c: -1, n: "073" },
    { s: "touch", c: -1, n: "074" },
    { s: "taste", c: -1, n: "075" }
  ].map(({s, c, n}) => ({
    advantage_id: `adv_${n}`,
    name: `Sens diminué (${s})`,
    type: "disadvantage",
    description: `${s.charAt(0).toUpperCase()+s.slice(1)} particulièrement diminué(e). Malus de -3.`,
    cost_pc: c,
    is_unique: false,
    family: "Sens diminué", family_limit: 1, subtype: s,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: { sense: s, penalty: -3 },
    mod_gauges: null,
    mod_identity: null,
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Corrigeable par chirurgie/implant."
  })),

  // ─── adv_076 : Fécondité ───
  {
    advantage_id: "adv_076",
    name: "Fécondité",
    type: "disadvantage",
    description: "Le personnage est fécond. Très grande valeur. Si découvert : traqué.",
    cost_pc: -3,
    is_unique: true,
    family: null, family_limit: null, subtype: null,
    mod_attribute: null, mod_value: null,
    mod_resistance: null, mod_res_value: null,
    mod_conditions: null,
    mod_gauges: null,
    mod_identity: { is_fertile: true },
    mod_savings: null,
    mod_monthly_income: null,
    mod_monthly_income_formula: null,
    mod_skill_points: null,
    mod_age: null,
    special_rule: "Si découvert : traqué comme Recherché. Ne concerne normalement pas les techno-hybrides."
  }
];

exports.up = async (knex) => {
  await knex.schema.createTable('ref_advantages', (table) => {
    table.text('advantage_id').primary();
    table.text('name').notNullable();
    table.text('type').notNullable();
    table.text('description');
    table.integer('cost_pc').notNullable();
    table.boolean('is_unique').defaultTo(false);
    table.text('family');
    table.integer('family_limit');
    table.text('subtype');
    table.text('mod_attribute');
    table.integer('mod_value');
    table.text('mod_resistance');
    table.integer('mod_res_value');
    table.jsonb('mod_conditions');
    table.jsonb('mod_gauges');
    table.jsonb('mod_identity');
    table.integer('mod_savings');
    table.integer('mod_monthly_income');
    table.text('mod_monthly_income_formula');
    table.integer('mod_skill_points');
    table.integer('mod_age');
    table.text('special_rule');
  });

  await knex('ref_advantages').insert([...ADVANTAGES, ...DISADVANTAGES]);
};

exports.down = async (knex) => {
  await knex.schema.dropTableIfExists('ref_advantages');
};
