// Styles inline de Sidebar.jsx — extrait de Sidebar.jsx (PLAN_REFACTOR_SIDEBAR.md, lot 2).
// Seul consommateur actuel : Sidebar.jsx (CHARMODAL-DEAD1 — l'autre consommateur d'origine,
// CharacterModal.jsx, était mort et a été supprimé ; DiceBreakdownPopover.jsx n'en a jamais dépendu).
export const styles = {
  sidebar: {
    position: 'relative',
    height: '100%',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
    overflow: 'hidden',
    userSelect: 'none',
  },
  resizeHandle: {
    position: 'absolute',
    left: '-3px',
    top: 0,
    width: '6px',
    height: '100%',
    cursor: 'col-resize',
    zIndex: 20,
  },
  toolsRow: {
    display: 'flex',
    gap: '6px',
    padding: '12px 12px 8px 16px',
    flexWrap: 'wrap',
    flexShrink: 0,
  },
  palette: {
    padding: '4px 12px 8px',
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    scrollbarGutter: 'stable',
  },
  paletteTitle: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '6px',
  },
  paletteGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
  },
  paletteGroup: {
    marginBottom: '8px',
  },
  paletteGroupLabel: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '4px',
  },
  matBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '4px',
    cursor: 'pointer',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  },
  roomTool: {
    borderRadius: '6px',
    padding: '8px',
    marginBottom: '10px',
  },
  roomToolToggle: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '7px 8px',
    borderRadius: '5px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  roomToolToggleState: {
    color: 'var(--color-primary)',
    fontSize: '10px',
    textTransform: 'uppercase',
  },
  roomToolModes: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '8px',
  },
  roomToolModeBtn: {
    flex: '1 1 72px',
    padding: '6px 0',
    borderRadius: '4px',
    fontSize: '11px',
    cursor: 'pointer',
  },
  roomToolGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '6px',
  },
  roomToolLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    color: 'var(--text-muted)',
    fontSize: '10px',
    textTransform: 'uppercase',
    marginTop: '8px',
  },
  roomToolSectionTitle: {
    marginTop: '10px',
    paddingTop: '8px',
    fontSize: '11px',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  roomToolSelection: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    padding: '7px 8px',
    borderRadius: '8px',
    fontSize: '11px',
    fontWeight: 600,
  },
  connectorPicker: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginTop: '8px',
    padding: '8px',
    borderRadius: '6px',
  },
  connectorPickerTitle: {
    color: 'var(--text-secondary)',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  connectorPickerEmpty: {
    color: 'var(--text-muted)',
    fontSize: '11px',
    lineHeight: 1.35,
  },
  connectorSelectedModel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: '7px 8px',
    borderRadius: '5px',
    fontSize: '11px',
  },
  connectorModelBtn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    width: '100%',
    padding: '7px 8px',
    borderRadius: '5px',
    fontSize: '12px',
    textAlign: 'left',
    cursor: 'pointer',
  },
  connectorColorPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '7px 8px',
    borderRadius: '5px',
  },
  connectorColorRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 34px 44px',
    gap: '6px',
    alignItems: 'center',
  },
  connectorColorLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    color: 'var(--text-secondary)',
    fontSize: '11px',
    minWidth: 0,
  },
  connectorColorReset: {
    height: '28px',
    padding: '0 8px',
    fontSize: '10px',
  },
  roomToolColorRow: {
    display: 'grid',
    gridTemplateColumns: '34px minmax(0, 1fr)',
    gap: '6px',
    alignItems: 'center',
  },
  roomToolColorInput: {
    width: '34px',
    height: '29px',
    padding: '2px',
  },
  roomToolRangeRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 32px',
    gap: '7px',
    alignItems: 'center',
  },
  roomToolRange: {
    width: '100%',
    accentColor: 'var(--color-primary)',
  },
  roomToolRangeValue: {
    color: 'var(--text-primary)',
    fontSize: '11px',
    fontFamily: "'Share Tech Mono', monospace",
    textAlign: 'right',
  },
  roomToolSmallBtn: {
    marginTop: '8px',
    alignSelf: 'end',
    padding: '6px 8px',
    fontSize: '11px',
  },
  roomToolHint: {
    marginTop: '8px',
    fontSize: '11px',
    lineHeight: 1.35,
  },
  tabContent: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },
  messages: {
    flex: 1,
    overflowY: 'auto',
    padding: '8px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  emptyMsg: {
    color: 'var(--text-muted)',
    fontSize: '12px',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '24px 12px',
    margin: 0,
  },
  message: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: '2px',
  },
  messageSystem: {
    display: 'flex',
    justifyContent: 'center',
    gap: '6px',
    alignItems: 'center',
  },
  msgSystemText: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontStyle: 'italic',
  },
  msgSystemErrorText: {
    fontSize: '11px',
    color: 'var(--color-danger)',
    fontStyle: 'italic',
    fontWeight: 600,
  },
  msgUser: {
    fontSize: '12px',
    fontWeight: '500',
  },
  msgTime: {
    fontSize: '10px',
    color: 'var(--text-muted)',
  },
  msgText: {
    width: '100%',
    margin: '2px 0 0',
    fontSize: '13px',
    color: 'var(--text-secondary)',
    lineHeight: '1.4',
    wordBreak: 'break-word',
  },
  chatForm: {
    display: 'flex',
    gap: '6px',
    padding: '8px 12px',
    borderTop: '1px solid var(--wiz-glass-border)',
    flexShrink: 0,
  },
  chatInput: {
    flex: 1,
    padding: '6px 10px',
    fontSize: '12px',
    outline: 'none',
  },
  persosList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '8px 12px',
  },
  newCharForm: {
    display: 'flex',
    gap: '6px',
    marginBottom: '4px',
  },
  charCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderRadius: '6px',
    cursor: 'grab',
  },
  charColor: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  charInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: 0,
  },
  charName: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  charOwner: {
    fontSize: '10px',
    color: 'var(--text-muted)',
  },
  charHidden: {
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  playersList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '8px 12px',
  },
  playerCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderRadius: '6px',
  },
  onlineDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  playerInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: 0,
  },
  playerNameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  playerName: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
  },
  playerCharacter: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  onlineLabel: {
    fontSize: '10px',
    flexShrink: 0,
  },
  undoRow: {
    display: 'flex',
    gap: '6px',
    margin: '4px 0 8px',
  },
  // Visuel (background/border/color, y compris :disabled) déjà porté par la classe CSS
  // .sidebar-undo-btn (index.css) — undoBtn ne garde plus que le layout. undoBtnDisabled retiré :
  // dead code, déjà couvert par .sidebar-undo-btn:disabled et jamais lu ici (lot 3, sous-lot 3b).
  undoBtn: {
    flex: 1,
    padding: '6px 8px',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '11px',
    letterSpacing: '0.4px',
    textTransform: 'uppercase',
  },
  btnAccept: {
    flex: 1,
    padding: '7px 0',
    fontSize: '11px',
  },
  btnAuto: {
    flex: 1,
    padding: '7px 0',
    fontSize: '11px',
  },
  btnRefuse: {
    flex: 1,
    padding: '7px 0',
    fontSize: '11px',
  },
  select: {
    padding: '6px 10px',
    fontSize: '12px',
    cursor: 'pointer',
    width: '100%',
  },
  // ── Séparateur Profil ──
  profilSeparator: {
    margin: '8px 0',
    flexShrink: 0,
  },
  // ── Config ──
  configContent: {
    padding: '16px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  // configSuccess : migré vers .sidebar-config-success (index.css), lot 3 sous-lot 3b.
  configField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  configLabel: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  configInput: {
    padding: '8px 10px',
    fontSize: '12px',
  },
  configColorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  // configColorPicker : migré vers .sidebar-config-color-picker (index.css), lot 3 sous-lot 3b.
  // ── Messages dés ──
  messageDice: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    padding: '6px 8px',
    clipPath: 'polygon(6px 0, 100% 0, 100% calc(100% - 6px), calc(100% - 6px) 100%, 0 100%, 0 6px)',
  },
  // diceCritSuccess/diceCritFail : migrés vers .sidebar-glass[data-crit] (index.css), lot 3 sous-lot 3b.
  diceHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexWrap: 'wrap',
  },
  diceIcon: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
  },
  // diceIconAnimating est appliqué inline via style spread — animation CSS via keyframes
  // injectés dans un tag <style> dans le composant Sidebar (une seule fois, hors du map)
  diceIconAnimating: {
    animation: 'diceRoll 0.8s ease-out',
  },
  diceBody: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '5px',
    paddingLeft: '2px',
  },
  diceFormula: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    fontFamily: 'monospace',
  },
  diceRolls: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontFamily: 'monospace',
  },
  diceEquals: {
    fontSize: '11px',
    color: 'var(--text-muted)',
  },
  diceTotal: {
    fontSize: '20px',
    fontWeight: '700',
    color: 'var(--text-primary)',
    fontFamily: 'monospace',
    marginLeft: 'auto',
  },
  // ── Bouton aide + Modale aide : migrés vers .sidebar-help-* / .sidebar-kbd (index.css),
  // PLAN_REFACTOR_SIDEBAR.md lot 3 — cluster 100% statique, plus de style={} sur ces éléments.
  // ── Message action entité (GM) ──
  messageAction: {
    padding: '8px 10px',
    borderRadius: '6px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  actionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  },
  actionIcon: {
    fontSize: '11px',
    flexShrink: 0,
  },
  actionTitle: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    flex: 1,
  },
  actionSub: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    paddingLeft: '2px',
  },
  actionMeta: {
    display: 'flex',
    gap: '10px',
    fontSize: '11px',
    color: 'var(--text-secondary)',
    flexWrap: 'wrap',
    paddingLeft: '2px',
  },
  actionBtns: {
    display: 'flex',
    gap: '6px',
    marginTop: '2px',
  },
  // pendingBadge : migré vers .sidebar-pending-badge (index.css), lot 3 sous-lot 3b.
}
