// Import ponctuel des dettes actives de docs/EN_COURS.md restées hors de bug_tickets (constat
// Saar 2026-08-22 : la table s'était accumulée sans jamais migrer vers le système de tickets réel,
// contrairement à l'intention documentée dans l'en-tête d'EN_COURS.md). Même patron que
// importBugIdentifie.js — script à usage unique, ré-exécutable sans doublon (skip si
// linked_bug_code déjà présent en base).
//
// Exclus délibérément (pas des bugs à tracker) :
//  - lignes déjà ✅ Résolu sans caveat (rien ne reste à faire) ou déjà nettoyées en 2026-08-22
//    (TC1/DCO1/VX1/COM26/CSPLAYERSTAB/INV5/COM20/COM21/AU1 — déjà en base ou closes)
//  - "Logs debug index.js — conservés volontairement" (décision assumée, pas un défaut)
//  - WIZLOCK1 (historique révolu, "pas un risque actif" — rien à corriger)
//  - DOC1 (tâche d'enrichissement continu, pas un bug ponctuel)
//  - WIZ27 (déjà ✅ Résolu, résidu = texte à rédiger par Saar, pas du code)
//
// status : 'new' si jamais investigué, 'triaged' si analysé mais pas corrigé, 'in_progress' si
// codé/corrigé mais en attente de validation navigateur, 'suspended' si bloqué sur une décision
// produit ou une repro manquante.
// priority : reprise du mot EN_COURS.md (Basse/Très basse→low, Moyenne→medium, Haute/Moyenne-Haute→high,
// Critique→critical).
//
// Lancement manuel : node --env-file=../.env server/src/scripts/importEnCoursDettes.js

import db from '../db/knex.js'

const ENTRIES = [
  { code: 'MONDEVALID1', title: 'Moteur de monde jamais validé en jeu réel sur une carte multi-étages complète', description: 'Fondation de tous les chantiers Étages/Ascenseur/Déplacement depuis la fusion Kiwi/Codex — jamais validé en jeu réel (Playwright + manuel) sur une carte multi-étages complète, seulement par tests Node (77+) et usage indirect.', domain: 'monde', priority: 'medium' },
  { code: 'AMMO-STD-MISMATCH1', title: 'Munitions "Projectile standard" 5.56/7.62mm avec formule ammo_effects empruntée à une autre munition', description: 'Darts 5.56mm ST - Projectile standard porte la formule d\'un projectile Explosif (FX=EXPLOSIVE) ; Darts 7.62mm ST - Projectile standard porte la formule d\'un projectile IEM (FX=IEM). Trouvé en vérifiant COM26 (déjà résolu). Nécessite de vérifier le calibrage RAW réel du "Projectile standard" avant toute correction.', domain: 'combat', status: 'new' },
  { code: 'SEED-ID-DETERM', title: 'ref_equipment.id non déterministe entre instances seedées séparément', description: 'server/src/db/seeds/2_seed_equipment.js laisse PostgreSQL générer l\'id à l\'insertion — idempotence garantie par name seul. Un id stable (UUID v5 dérivé d\'une clé source) rendrait id portable comme name l\'est déjà.', domain: 'infrastructure', priority: 'low' },
  { code: 'HORLOGE1', title: 'Horloge de campagne masquée en Combat/Édition — validation en jeu en attente', description: 'GameTimeWidget (Sidebar.jsx) codé pour être masqué en mode Combat et Édition, gate sur `mode`. En attente de validation en jeu par Saar.', domain: 'autre', status: 'in_progress', priority: 'low' },
  { code: 'EQSKILLS1', title: 'ref_equipment_skills jamais consommée en jeu', description: '"Compétences boostées/requises" — seulement écrite/relue par l\'API admin routes/equipment.js, aucun calcul ne la lit. Fusion avec ref_equipment_skill_assoc possible mais non prioritaire.', domain: 'personnage', priority: 'low' },
  { code: 'TIRMODE1', title: '"Changer le mode de tir" — non implémenté', description: 'Mécanique de changement de mode de tir jamais implémentée.', domain: 'combat', status: 'new', priority: 'medium' },
  { code: 'DR2', title: 'Drone : déplacement absent', description: 'Aucune mécanique de déplacement pour les drones.', domain: 'combat', priority: 'low' },
  { code: 'EAU1', title: 'Nappe d\'eau ambiante retirée — validation en jeu en attente', description: 'computeSurfaceWaterCells/WaterSheets retirée (improvisation client hors autorité serveur, décision Saar 2026-07-29) — eau en jeu recentrée sur l\'effet runtime "inondation" déjà câblé. Codé, tests/build/lint OK, validation en jeu par Saar avant clôture.', domain: 'monde', status: 'in_progress', priority: 'low' },
  { code: 'CURSEUR-DEFAUT1', title: 'Curseur natif par défaut — validation visuelle en attente', description: 'CURSEUR.svg (curseur natif cursor:url(), pas overlay DOM) par défaut hors combat. Codé, build OK — validation en jeu par Saar (précision du clic, taille, fond transparent) avant clôture.', domain: 'autre', status: 'in_progress', priority: 'low' },
  { code: 'PLAN_RW_SYSCOMBAT-LOT7', title: 'confirmMeleeDefense — chemin attaquant PJ non testé en jeu', description: 'Branchement post-hit codé + fixture validée (10 passes) + confirmé en jeu pour l\'attaquant PNJ. Chemin attaquant PJ (resolveMeleeDefenseHitAttackerPj) non testé en jeu (Saar ne peut pas reproduire ce cas actuellement) — reste couvert par fixture seulement.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'INI1', title: 'Surprise critique (roll=1) → initiative=1', description: 'Cas de surprise critique non géré pour l\'initiative.', domain: 'combat', priority: 'low' },
  { code: 'INI2', title: 'Initiative non recalculée après blessure en combat', description: 'Une blessure en cours de combat ne déclenche pas de recalcul d\'initiative.', domain: 'combat', priority: 'low' },
  { code: 'P-SRV-5', title: 'Ports Docker non restreints sur le serveur distant', description: 'Héritage de la collaboration Kiwi — ports Docker (postgres/redis/minio) non restreints sur le serveur distant.', domain: 'infrastructure', status: 'new', priority: 'low' },
  { code: 'CS4', title: 'Catégorie "Techniques" + liste compétences non implémentée', description: 'Cluster O — catégorie de compétences "Techniques" et sa liste non implémentées, absentes du registre BUGIDENTIFIE.md d\'origine.', domain: 'personnage', status: 'new', priority: 'medium' },
  { code: 'CS5', title: 'Compétence réservée (X) : ouverture 1 XP, reste -3 — non implémenté', description: 'Cluster O — mécanisme d\'ouverture d\'une compétence réservée (X) non implémenté, absent du registre BUGIDENTIFIE.md d\'origine.', domain: 'personnage', status: 'new', priority: 'medium' },
  { code: 'MUT3-LOT7', title: 'Effets mutations/avantages — Lot 7 (Narratif/économie) restant', description: 'Lots 1-6 (attributs, résistances, armure/arme naturelle, déblocage de compétence, identité) clos et fonctionnels. Lot 7 (Narratif/économie) reste à détailler.', domain: 'personnage', status: 'new', priority: 'low' },
  { code: 'WIZ-2', title: 'Deux compteurs PC désynchronisés (header vs CareersAllocator)', description: 'Cause racine plus large que CareersAllocator seul (Step3Mutations/Step5Advantages aussi) — getStepBudget(excludeStep) corrigé. Codé, scénario réel navigateur non testé.', domain: 'wizard', status: 'in_progress', priority: 'medium' },
  { code: 'WIZ-3', title: 'Formation "apprentissage_technique" : choix de spécialité non implémenté', description: 'Choix de spécialité pour la formation "apprentissage_technique" non implémenté (COUCHE 4c).', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'WIZ7', title: 'Étape 7 : l\'âge progressait à chaque test sans jamais régresser', description: 'char_archetype.age stockait l\'âge final, getStep4State le renvoyait comme âge de base, cumul à chaque réhydratation. Colonne base_age séparée ajoutée (migration 237). Codé, scénario réel non testé ; personnages déjà en création non réparés rétroactivement (base_age NULL → repli 16).', domain: 'wizard', status: 'in_progress', priority: 'medium' },
  { code: 'WIZ8', title: 'getStep3State/getStep5State omettaient mutationsMeta/advantagesMeta/pcNet/finalAge', description: '4 champs consommés par WizardReview.jsx et creationStore.js, effacés dès le premier écho WIZARD_STATE_SYNC. 4 champs ajoutés, requêtes vérifiées contre des fiches réelles. Codé, scénario réel non testé.', domain: 'wizard', status: 'in_progress', priority: 'medium' },
  { code: 'WIZ22', title: 'Bloc "Compétences professionnelles" vs grille de répartition — confusion métiers différents', description: 'Les deux blocs pouvaient porter sur des métiers différents sans que ce soit clair. Bloc réintégré, conditionné à !isAdded. Codé, scénario réel non testé.', domain: 'wizard', status: 'in_progress', priority: 'medium' },
  { code: 'WIZ-ROUNDTRIP-DEPWARN', title: 'DeprecationWarning pg dans creationRoundTrip.test.mjs (STEP5)', description: 'addAdvantage lance un Promise.all de plusieurs requêtes sur la même transaction (connexion unique) — deviendra un throw en pg 9. Aucune erreur aujourd\'hui, résultats corrects.', domain: 'infrastructure', status: 'new', priority: 'low' },
  { code: 'WIZ13', title: '"Fiche introuvable" à l\'Étape 1 pour un MJ créant son propre personnage', description: 'isGmView testé seul pour détecter un MJ qui revient consulter un autre brouillon, mais un MJ démarrant SON PROPRE personnage obtient aussi isGmView=true → resetCreation() efface sheetId. Condition remplacée par ownerUserId !== user.id. Codé, scénario réel non testé.', domain: 'wizard', status: 'in_progress', priority: 'high' },
  { code: 'WIZ12', title: 'ref_advantages.name avec termes anglais non traduits entre parenthèses', description: '14 lignes corrigées (migration 239 : vue/ouïe/odorat/toucher/goût, maladie, drogue) ; poison/radiation laissés (mots identiques FR/RAW). Codé, scénario réel non testé.', domain: 'wizard', status: 'in_progress', priority: 'low' },
  { code: 'WIZ11', title: 'Diffusion live MJ (Step4 Avantages & Revers) manquait proAdvantages/randomPicks', description: 'useEffect de diffusion appelait buildPayload() sans lister ces champs en deps. buildPayload passé en useCallback. Codé, scénario réel (MJ observateur) non testé.', domain: 'wizard', status: 'in_progress', priority: 'medium' },
  { code: 'WIZ10', title: 'Mutation "Parasite" sans jet pour le nombre de parasites', description: 'RAW "Lancez 1D4" jamais instruit, ni en tirage ni en achat délibéré. Migration 238 : 4 sous-types "1 à 4 parasites" ajoutés (même mécanisme que "Caractère génétique animal"). Codé, scénario réel non testé.', domain: 'wizard', status: 'in_progress', priority: 'low' },
  { code: 'WIZ9', title: 'Compétences à prérequis SKILL_MIN achetables sans vérification par défaut', description: 'settings.skill_prerequisites par défaut à false contredisait le RAW ("NÉCESSAIRE (OPTIONNEL)"). Défaut basculé à true. Codé, non testé : achat réel d\'une compétence gated en navigateur.', domain: 'wizard', status: 'in_progress', priority: 'medium' },
  { code: 'CAR1', title: 'Mécanisme "au choix" (conditional:true) non implémenté', description: '34 occurrences sur les lots 2-6 des carrières — Step4 UI.', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'CAR2', title: 'ref_background_skills.skill_id sans FK vers ref_skills.id', description: 'Même défaut que ref_career_skills avant migration 111 — préventif, pas de bug connu à ce jour.', domain: 'infrastructure', status: 'new', priority: 'low' },
  { code: 'CAR3', title: 'Prérequis carrières non insérés dans ref_career_prerequisites', description: 'Table vide (vérifié 2026-08-22) — espion, soldat_elite_*, officier_militaire_souterrain, etc. sans prérequis en base. Nécessite le texte RAW exact avant toute migration.', domain: 'wizard', status: 'suspended', priority: 'medium', admin_notes: 'Bloqué : besoin du texte RAW des prérequis de carrières (Livre de Base) — ne pas deviner le contenu.' },
  { code: 'DBG-C1', title: 'character.user_id null quand le MJ crée pour un joueur absent (steps 1-3)', description: 'Vérifié 2026-08-22 : le chemin targetUserId de POST /api/creation/start exige déjà que le joueur ciblé soit membre de la campagne (rejette sinon) — contredit le scénario "joueur absent" du ticket. Soit le ticket est périmé, soit il vise un autre chemin de code non encore localisé (characters.js direct ?).', domain: 'wizard', status: 'new', priority: 'medium', admin_notes: 'Diagnostic à approfondir avant tout correctif — pas confirmé reproductible sur le chemin déjà audité (2026-08-22).' },
  { code: 'OPT-W1', title: '3/11 options de campagne sans effet mécanique branché', description: 'revers, skill_natural_prog, celebrity restent sans câblage — le reste (ambiance, random_mutations, feminin_bonus, random_pro_advantages, skill_prerequisites, skill_max_level, young_penalty, polaris_latent) déjà câblé au fil des sessions.', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'OPT-W2', title: 'style={} visuel dans les 7 fichiers campaignSettings/* (convention CSS non suivie)', description: 'Convention PC47 (className plutôt que style inline pour le visuel) non appliquée dans client/src/components/campaignSettings/*.', domain: 'wizard', status: 'new', priority: 'low' },
  { code: 'MUT1', title: 'Mutations Purulence/Organe sensoriel manquant avec cost_pc négatif incohérent', description: 'cost_pc=-2 incohérent avec la convention positive des Difformités — Step3Mutations.jsx (cost_pc>=0) pouvait les exclure de la liste achetable. Corrigé. Codé, scénario réel non testé.', domain: 'wizard', status: 'in_progress', priority: 'low' },
  { code: 'ADV3', title: 'Bénéfices de carrière débloquant une compétence — non géré', description: 'Compétence/mutation "développée automatiquement" via tirage de carrière — aucun câblage vers char_skills/char_mutations.', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'WIZ4', title: 'Mini-stepper (isClickable) ne revalide jamais les blocages durs de la sous-step quittée', description: 'Ex. retirer sa seule carrière puis cliquer directement sur une sous-step déjà "reachable". Filet serveur (reconcileCreation STEP4) empêche toute donnée invalide persistée — juste un rejet tardif au lieu d\'un blocage immédiat.', domain: 'wizard', status: 'new', priority: 'low' },
  { code: 'DOC2', title: 'docs/SYSTEME/REGLES_LdB.md mal placé, encodage mojibake, doublon probable', description: 'Dump brut d\'extraction LdB — devrait être dans REGLES/ (RegleDocumentaire.md Règle 8), doublon probable avec docs/REGLES/REGLESYSCOMBAT.md. Bandeau d\'avertissement déjà ajouté.', domain: 'infrastructure', status: 'new', priority: 'low' },
  { code: 'GEOM1', title: 'PLAN_GEOMETRIE.md jamais codé — Codex hors projet, réponse attendue ne viendra jamais', description: 'Rampe/Slope/Porte (Atelier du GM) jamais codé, obsolète depuis le nouveau builder selon Saar. Attendait une réponse de Codex sur la réutilisabilité de fragments existants — Codex a quitté le projet depuis (2026-08-04), la question ne sera jamais répondue par lui.', domain: 'monde', status: 'suspended', priority: 'low', admin_notes: 'Codex hors projet depuis 2026-08-04 (vérifié) — décision (archiver/supprimer) à reprendre avec Saar seul, sans attendre de réponse.' },
  { code: 'INI4', title: 'initiative jamais remise à base_ini en fin de tour', description: 'Item 96, Session 166 — codé, scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'low' },
  { code: 'INI5', title: 'CaC : forfait Initiative de déclaration (-3/-5) doublon avec le décalage de phase', description: 'Sans base RAW — item 111, Session 176, audit tranché, retiré. Scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'low' },
  { code: 'COM24', title: 'Bonus "deux armes" (+3 CaC) déconnecté de l\'arme réellement déclarée', description: 'Item 112, Session 176 — mécanisme complet codé (miroir Tir). Scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'MELEE-MR', title: 'Dégâts CaC calculés sans le MR', description: 'Item 97, Session 166 — codé, scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'DEF5', title: '"Cible sans défense" (+5, pas d\'opposition) absent en Tir ET CaC', description: 'Item 98, Session 166 — codé, scénario réel navigateur non testé ; tir de drone non couvert.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'SURPRISE1', title: 'is_surprised jamais remis à false après COMBAT_START', description: 'Item 110, Session 176 — codé, scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'TIRIMP', title: 'Garde serveur absent sur "Tir impossible"', description: 'Item 99, Session 166 — codé, scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'WNDMORT', title: 'Malus blessure "mortelle" codé -20 fixe au lieu de bloquer les Tests', description: 'Item 100, Session 166 — corrigé. Scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'WNDMORT-UI', title: 'Fenêtre de déclaration sans repli visuel pour Blessure mortelle', description: 'Le serveur rejette déjà, l\'UI ne prévenait pas avant. Bandeau d\'avertissement + tuiles grisées codés. Scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'low' },
  { code: 'WNDMORT-HORSCOMBAT', title: 'Test générique hors-combat non gardé pour Blessure mortelle', description: 'socketEntity.js — le test générique hors-combat n\'est pas gardé pour la Blessure mortelle. Garde + bandeau centré codés (décision Saar : bandeau centré). Scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'low' },
  { code: 'EXOARM-COMBATFILE', title: 'Chantier Exo-armures — Lots 1-4/A-D intégralement codés, validation jeu réel manquante', description: 'PLAN_EXOARMURE.md Lots 1-4 (mécaniques combat) et A-D (finition fiche) intégralement codés et testés (Node/PostgreSQL réel). Aucune exo-armure jouée de bout en bout en combat réel à ce jour. Détail complet docs/EN_COURS.md et docs/JOURNAL8.md.', domain: 'personnage', status: 'in_progress', priority: 'high' },
  { code: 'ETATSPERS-LOT2C', title: 'combat_roster.state_position/state_weapon non retirées', description: 'entry (socketCombatAnnouncement.js) toujours lu directement depuis combat_roster, pas migré vers characterStateService. Différé volontairement (plus d\'urgence de fusion).', domain: 'combat', status: 'new', priority: 'low' },
  { code: 'CATASTROPHE-L1', title: 'Catastrophe automatique en combat — moteur codé, 10 conséquences narratives', description: 'Jet 1D10 + validation MJ codés et testés (8 tests Node, PostgreSQL réel). Les 10 conséquences restent définitivement narratives (MJ applique à la main). Scénario réel navigateur non testé.', domain: 'combat', status: 'in_progress', priority: 'medium' },
  { code: 'SECU-EMAIL1', title: 'Aucune mécanique d\'envoi d\'email sur le serveur de déploiement', description: 'Bloque toute fonctionnalité qui en dépendrait (vérification d\'adresse, notification de blocage, reset de mot de passe par email).', domain: 'infrastructure', status: 'new', priority: 'low' },
  { code: 'WIZ29', title: 'Écran blanc Step4 Avantages & Revers sur une carrière à 5 ans', description: 'React démonte l\'arbre sur exception non catchée puis retour à l\'étape 0. Cause non identifiée en lecture statique (blockCount/career.years/setbackBlockCount sains dans ce scénario). Pas de repro fiable ni de stack trace disponible.', domain: 'wizard', status: 'new', priority: 'medium', admin_notes: 'Filet WizardStepErrorBoundary posé (logge [DBG-WIZCRASH] avec stack complète) au lieu de l\'écran blanc, sans rien réinitialiser côté store — reste à reproduire en navigateur.' },
  { code: 'WIZ38', title: 'Step4 Profession : coût des compétences réservées (X) mal facturé à l\'achat', description: 'handleAllocInc/Dec utilisent base=0 au lieu de null pour une compétence (X) jamais apprise — un seul clic facture toute la montée -3→1 d\'un coup au lieu de niveau par niveau. Dépend de WIZ39 (marqueur erroné en base sur l\'exemple testé, Administration/Gestion).', domain: 'wizard', status: 'new', priority: 'high' },
  { code: 'WIZ41', title: 'Step6 Matériel : filtres du catalogue insuffisants pour trouver une arme par type', description: '"arme de poing ok, mais fusil ? arme à deux mains ?" — aucune facette sur le nombre de mains requis (ref_location). Piste : facette dérivée réutilisant slotOptionsForItem.', domain: 'wizard', status: 'new', priority: 'low' },
  { code: 'WIZ42', title: 'Step6 Matériel : pas de bouton visible pour que le MJ valide le matériel', description: 'Le bouton existe déjà en code (gaté inWizard && isGm && !validated_by_gm) — cause exacte (aucun item en attente, isGm/inWizard incorrects, ou bouton peu visible) non tranchée. Saar demande un débat sur la pertinence du mécanisme "VALIDÉ" avant tout correctif.', domain: 'wizard', status: 'suspended', priority: 'medium', admin_notes: 'Ne pas coder de correctif tant que la discussion produit demandée par Saar n\'a pas eu lieu.' },
  { code: 'WIZ44', title: 'Step6 Matériel : pas de bouton pour changer la quantité d\'un objet déjà ajouté', description: 'Le serveur sait déjà décrémenter partiellement (DELETE inventaire accepte {quantity}) mais le client ne l\'utilise jamais.', domain: 'wizard', status: 'new', priority: 'low' },
  { code: 'WIZ45', title: 'Step7 Récap affiche des données périmées ET le personnage se finalise avec ces données périmées', description: 'Perte réelle de choix joueur confirmée par le beta-testeur (dépense de PC en Step1 après retour arrière, jamais reflétée en Step7 ni dans la fiche finalisée). Cause racine trouvée : seul le bouton "Suivant →" de chaque étape committe au store — Précédent et le stepper ne font que setStep(n), abandonnant silencieusement toute édition locale non validée par ce chemin précis.', domain: 'wizard', status: 'new', priority: 'high' },
  { code: 'WIZ30', title: 'Step1 "Taille" libellée "(m)" alors que la saisie naturelle est en cm', description: 'Champ narratif, aucune mécanique n\'en dépend. Bascule en cm exige une migration de conversion (×100) des personnages déjà saisis — décision de Saar en attente.', domain: 'wizard', status: 'suspended', priority: 'low' },
  { code: 'WIZ31', title: 'Header wizard non fixé pendant le scroll d\'une étape longue', description: '.wiz-shell sans hauteur plafonnée, st.body sans overflow-y:auto propre — le header (compteur PC + navigation) sort du champ au scroll.', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'WIZ32', title: 'Diffusion live MJ→PJ absente hors verrouillage', description: 'WIZARD_LIVE_UPDATE symétrique côté serveur mais WizardCreation.jsx ne restitue le brouillon live que pour un MJ observant un joueur, jamais l\'inverse — contredit l\'exigence documentée de Saar. Non trivial : généraliser sans écraser la frappe en cours du joueur si édition simultanée.', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'WIZ33', title: 'Step3 Mutations : pas de granularité de broadcast sur le tirage/l\'achat', description: 'Probablement rattaché à WIZ32 (même mécanisme liveOr/gmSyncKey) — à re-vérifier une fois WIZ32 tranché.', domain: 'wizard', status: 'new', priority: 'low' },
  { code: 'WIZ34', title: 'Step4 Expérience : broadcast MJ s\'interromprait à la sous-étape Formation', description: 'Sens du flux concerné à clarifier (MJ→PJ qui ne fonctionne jamais selon WIZ32, ou PJ→MJ qui fonctionne par ailleurs) — repro exacte nécessaire avant tout correctif.', domain: 'wizard', status: 'suspended', priority: 'low' },
  { code: 'WIZ35', title: 'Step4 Profession : affordance de clic insuffisante', description: '"l\'UI ne donne pas envie de cliquer" — retour UX nécessitant un passage design (hover state, curseur, contraste), pas un correctif ponctuel.', domain: 'wizard', status: 'new', priority: 'low' },
  { code: 'WIZ37', title: 'Step4 démarre sur Origine au lieu d\'Âge', description: 'Comportement délibéré documenté en commentaire (age a toujours un défaut, ne peut pas servir de marqueur "sous-étape visitée") — écart avec la demande actuelle de Saar, décision à trancher avant de coder.', domain: 'wizard', status: 'suspended', priority: 'low' },
  { code: 'WIZ36', title: 'Step1 : décompte de PC afficherait 15 au lieu de 20 au démarrage', description: 'Non reproduit en lecture statique (PC_TOTAL=20, ledger neuf à 0 partout). Nouvel indice de repro (compteur monté à 17 puis "redevenu normal" après sélection des métiers) — audit complet demandé par Saar pas encore fait.', domain: 'wizard', status: 'suspended', priority: 'low' },
  { code: 'COM-RESO1', title: 'Combat — phase Résolution corrompue : double action PNJ + régression de phase PJ', description: 'Le PNJ exécute deux actions (la sienne + celle de son adversaire), le PJ repasse en phase Annonce. Signalé critique par Saar, serveur distant. Symptôme trop grave/précis pour être deviné sans repro instrumentée.', domain: 'combat', status: 'suspended', priority: 'critical', admin_notes: 'Ne pas coder de correctif sans repro instrumentée. Bloqué sur l\'absence de logs — débloqué potentiellement par ADMIN-LOGS1 (/admin/logs, 2026-08-22) : capturer la séquence complète Annonce→Résolution à la prochaine occurrence.' },
  { code: 'INV7-MIGRATION-LINK', title: 'Piste migration écartée pour INV7', description: 'INV7 (équipement armes/armure) suspecté lié à une désynchronisation de migrations (ticket 221f493a) — vérifié 2026-08-22 : ce ticket précis (exo-armures/export Excel) est résolu et sans rapport avec char_inventory/ref_equipment. Cause réelle d\'INV7 encore à chercher si le symptôme persiste.', domain: 'infrastructure', status: 'new', priority: 'low' },
  { code: 'COM-MOVEUI1', title: 'Fenêtre de déplacement toujours visible, réapparaît sans cesse', description: 'Comportement volontaire (décisions Saar 2026-07-31/2026-08-01, useAutoMoveMode.js) — contredit un ressenti récent de Saar signalé comme gênant. Vérifier si le ressenti a changé avant de toucher au code.', domain: 'combat', status: 'suspended', priority: 'medium', admin_notes: 'Décision produit à reconfirmer avec Saar, pas un bug de code — contredit 2 décisions passées documentées.' },
  { code: 'INV6', title: 'Fenêtre Commerce : permettre de l\'agrandir verticalement', description: 'Listes catalogue/inventaire actuellement en scroll interne contraint (maxHeight 260px). Aucune poignée de redimensionnement manuel n\'existe nulle part dans le projet — vraie nouvelle capacité à concevoir, potentiellement généralisable à d\'autres fenêtres flottantes.', domain: 'personnage', status: 'new', priority: 'low' },
  { code: 'INV2', title: 'Les joueurs obtiennent des objets gratuitement via le bouton Ajouter (même accès que le MJ)', description: 'POST /char-sheet/:characterId/inventory ne déduit jamais sols — seule différence MJ/joueur est validated_by_gm. Le prix existe déjà en base (ref_equipment.price). Correctif implique une vraie mécanique (déduire sols, bloquer si insuffisant) — décision produit avant code (débiter à l\'ajout ou à la validation MJ ?).', domain: 'personnage', status: 'new', priority: 'high' },
  { code: 'INV3', title: 'Drag & drop inventaire sans affordance visuelle', description: 'Le drag & drop existe (useDraggable/useDroppable, Sac/Ceinture/Coffre) mais aucune affordance visuelle (curseur grab, icône, hint) — les joueurs ne s\'en rendent pas compte.', domain: 'personnage', status: 'new', priority: 'low' },
  { code: 'WIZ39', title: 'Données — 76 compétences du catalogue avec mauvais marqueur (X)/(-3)', description: 'Audité RAW ligne par ligne (pas un sondage). 61 lignes : (X) manquant (Sciences spécialisées, Langues, Pilotage, Commerce/Trafic, Armures atmosphériques...). 15 lignes : (-3) manquant (autres Commerce/Trafic, Armures spatiales, Expression artistique, Arts martiaux...). Impact mécanique différent des deux (gate d\'accès+coût vs malus de départ). Aucune correction faite — migration de données touchant potentiellement des personnages déjà créés, décision de Saar nécessaire sur la portée.', domain: 'wizard', status: 'suspended', priority: 'high', admin_notes: 'Bloqué sur la décision de Saar : corriger uniquement le seed (futurs personnages) ou aussi les personnages déjà créés avec le mauvais coût.' },
  { code: 'WIZ40', title: 'Step6 Matériel : broadcast MJ→PJ cassé sur les jauges (Biens non matériels)', description: 'Le joueur ne voit pas les ajustements de jauge faits par le MJ. Mécanisme a l\'air symétrique en lecture (resolveInventoryBroadcastRoom diffuse, useWizardInventorySync écoute sans condition de rôle) — cause racine non trouvée, repro nécessaire (MJ et joueur simultanés sur Step6, capture réseau/socket des deux côtés).', domain: 'wizard', status: 'new', priority: 'medium' },
  { code: 'EXOARM-MULTIADV1', title: 'atkEnemyType/defEnemyType traite toute exo comme "pj" par défaut de code', description: 'character.type === \'pj\' ? \'pnj\' : \'pj\' — un personnage type=\'exo\' est toujours traité comme \'pj\', jamais \'pnj\', même si le pilote est un PNJ. Aucune exo-armure réelle en jeu à ce jour.', domain: 'combat', status: 'new', priority: 'low' },
]

async function run() {
  const admin = await db('users').where({ role: 'admin' }).first('id', 'username')
  if (!admin) throw new Error('Aucun compte admin trouvé — bootstrap requis avant import.')

  let inserted = 0
  let skipped = 0

  for (const entry of ENTRIES) {
    const existing = await db('bug_tickets').where({ linked_bug_code: entry.code }).first('id')
    if (existing) { skipped++; continue }

    await db('bug_tickets').insert({
      reporter_id: admin.id,
      origin: 'admin',
      category: entry.category || 'bug',
      domain: entry.domain || null,
      title: entry.title,
      description: entry.description,
      status: entry.status || 'triaged',
      priority: entry.priority || null,
      cluster_label: entry.cluster_label || null,
      linked_bug_code: entry.code,
      admin_notes: entry.admin_notes || null,
    })
    inserted++
  }

  console.log(`[IMPORT-ENCOURS-DETTES] ${inserted} tickets créés, ${skipped} déjà présents (linked_bug_code), par ${admin.username}.`)
  await db.destroy()
}

run().catch(err => { console.error(err); process.exit(1) })
